before_script:
  ## docker login
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

stages:
  - build
  - deploy

build-image-prod:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG .
    - docker push $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG
  only:
    - main

deploy-prod:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_HOST "
          docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
          docker pull $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG && 
          docker run -d --name $PROD_CONTAINER_NAME -e PG_HOST=$PG_HOST -p 3000:3000 $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG"
  only:
    - main