stages:
  - build
  - deploy

build-image-prod:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: '/certs'
  before_script:
    ## docker login
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG .
    - docker push $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG
  only:
    - main

deploy-prod:
  stage: deploy
  image: teke97/sshpass_alpine
  script:
    - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_HOST "
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
      docker stop $PROD_CONTAINER_NAME  || true &&
      docker rm $PROD_CONTAINER_NAME || true &&
      docker image rm $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG || true &&
      docker run -d --name $PROD_CONTAINER_NAME -e PG_HOST=$PG_HOST
      -e PG_DB=tripoasia_db -e PG_USER=tripoasia -e PG_PASSWORD=12345 -e TOKEN_KEY=tripoasia
      -p 3000:3000 $REGISTRY_USER/$PROJECT_NAME-$PROD_IMAGE:$PROD_TAG"
  only:
    - main
