version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: node/node_live_app
    ports:
      - '3000:3000'
    environment:
      - PG_DB=node_db_test
      - PG_USER=db_username
      - PG_PASSWORD=12345
      - PG_HOST=node_db
      - NODE_ENV=production
    depends_on:
      - node_db
    entrypoint: ['/bin/bash', './entrypoint.sh']
    # command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=node_db_test
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_test_data:/var/lib/postgresql/data
volumes:
  node_db_test_data: {}
