version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: tripoasia/node_live_app
    ports:
      - '3000:3000'
    environment:
      - PG_DB=tripoasia_db
      - PG_USER=tripoasia
      - PG_PASSWORD=12345
      - PG_HOST=node_db
      - NODE_ENV=dev
    depends_on:
      - node_db
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tripoasia_db
      - POSTGRES_USER=tripoasia
      - POSTGRES_PASSWORD=12345
    # volumes:
    #   - triposasia_db_data:/var/lib/postgresql/data
volumes:
  triposasia_db_data: {}
